name: CI/CD Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "test" ]

jobs:

  compile:
    runs-on: ec2-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci

  security-check:
    runs-on: ec2-hosted
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS Scan (via Docker)
        run: docker run --rm -v $(pwd):/project aquasec/trivy fs /project
      - name: Gitleaks Code Scan (via Docker)
        run: docker run --rm -v $(pwd):/app zricethezav/gitleaks:latest detect --source=/app --report-format=json --report-path=/app/gitleaks-report.json

  test:
    runs-on: ec2-hosted
    needs: security-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test

  sonar_scan:
    runs-on: ec2-hosted
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials for Secrets Manager access
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::634277304418:role/nodejs-cicd-role

      - name: Get Sonar secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secrets: |
            SONAR_TOKEN,nodejs_github_actions:SONAR_TOKEN
            SONAR_HOST_URL,nodejs_github_actions:SONAR_HOST_URL

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}

      - name: Install jq locally
        run: |
          curl -L -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x jq
          echo "$PWD" >> $GITHUB_PATH

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}

  docker_build_and_push:
    runs-on: ec2-hosted
    needs: sonar_scan
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials for Secrets Manager access
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::634277304418:role/nodejs-cicd-role

      - name: Get DockerHub secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secrets: |
            DOCKERHUB_USERNAME,nodejs_github_actions:DOCKERHUB_USERNAME
            DOCKERHUB_TOKEN,nodejs_github_actions:DOCKERHUB_TOKEN

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with version tag
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:latest .
          docker tag ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:latest ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:${{ github.sha }}

      - name: Trivy Image Scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:latest

      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:${{ github.sha }}

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Configure AWS credentials for Secrets Manager access
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::634277304418:role/nodejs-cicd-role

      - name: Get DockerHub and app secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secrets: |
            DOCKERHUB_USERNAME,nodejs_github_actions:DOCKERHUB_USERNAME
            DOCKERHUB_TOKEN,nodejs_github_actions:DOCKERHUB_TOKEN
            DB_URL,nodejs_github_actions:DB_URL
            API_KEY,nodejs_github_actions:API_KEY

      - name: Setup SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2 via SSH and run container
        env:
          DB_URL: ${{ env.DB_URL }}
          API_KEY: ${{ env.API_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
            docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ env.DOCKERHUB_TOKEN }}
            docker pull ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:latest
            docker stop nodeapp || true && docker rm nodeapp || true
            docker run -d -p 3000:3000 --restart unless-stopped --name nodeapp \
              -e DB_URL=\$DB_URL \
              -e API_KEY=\$API_KEY \
              ${{ env.DOCKERHUB_USERNAME }}/nodejs-cicd-app:latest
          "
