name: OIDC Role Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::634277304418:role/nodejs-github-actions-role
          aws-region: ap-southeast-1

      - name: Test AWS access
        run: aws sts get-caller-identity
