name: CI/CD Pipeline

on:
  push:
    branches: [ "GAR-Repo" ]

jobs:
  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci

  test:
    runs-on: self-hosted
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test

  docker_build_and_push:
    runs-on: self-hosted
    needs: test
    env:
      IMAGE_NAME: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/nodejs-cicd-app"
    steps:
      - uses: actions/checkout@v4

      - name: Load .env from Secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          set -a
          source .env
          set +a

      - name: Check Docker Access
        run: |
          whoami
          groups
          docker ps || echo "Docker access failed"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > gcp-key.json 2>/dev/null || echo "$GCP_SA_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          docker buildx build --push \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} .

      - name: Trivy Image Scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image $IMAGE_NAME:latest

  deploy_to_local:
    runs-on: self-hosted
    needs: docker_build_and_push
    env:
      IMAGE_NAME: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/nodejs-cicd-app"
    steps:
      - name: Stop Existing Container (if any)
        run: |
          docker ps -q --filter "name=nodeapp" | grep -q . && \
          docker stop nodeapp && docker rm nodeapp || echo "No container to stop"

      - name: Pull Latest Docker Image
        run: docker pull $IMAGE_NAME:latest

      - name: Run New Container with Restart Policy
        run: |
          docker run -d -p 80:3000 \
            --restart unless-stopped \
            --name nodeapp \
            $IMAGE_NAME:latest
